### ISSUE TITLE
Adjective and Noun List in Other Languages

### ISSUE THREAD

**Issue by montdor** [NaturalLanguagePasswords/system#1]
Hi!

Amazing project! I am a big fan of diceware, but I think this method may take the cake in terms of passphrase generation. I found a very interesting idea online of using a multilingual password to make the entropy even higher. I can't currently find word lists long enough to fit this system, but I think it should be possible and would give some interesting options for password combinations, especially for multilingual individuals.

Keep up the awesome work!

Edit: I did find a corpus from the Royal Spanish Academy containing 10,000 lemmas with their parts of speech, so that may be useful (http://web.frl.es/CORPES/org/publico/pages/estad/10000_lemas.txt)

**Comment by NaturalLanguagePasswords** [comment]
Thanks for the idea.  English is all I'm capable of.  The system is suitable for any language with adjectives and nouns though.
